---
language: python
python: "2.7"

env:
  - SITE=playbook.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl -y

install:
  - pip install -U ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Travis has java built-in. This is a good case for Voom Test-Flight or Docker Hub.
  # Run the role/playbook with ansible-playbook.
  # - "ansible-playbook -i tests/inventory tests/main.yml --connection=local --sudo -vvvv"

  # Run java version
  - "java -version"